# Generated by Django 5.0.3 on 2024-05-09 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='about',
            field=models.TextField(help_text='Введите сведения о жанре', null=True, verbose_name='Сведения о жанре'),
        ),
    ]
