# Generated by Django 5.0.3 on 2024-05-09 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_genre_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='category',
            new_name='genre',
        ),
    ]
