# Generated by Django 5.0.3 on 2024-05-10 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_rename_category_subscription_genre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
