openapi: 3.0.2
info:
  title: 'OpenAPI спецификация'
  version: ''
servers:
    - url: http://127.0.0.1:8000/
paths:
  /api/v1/authorlist/:
    get:
      operationId: listAuthors
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Authors'
          description: ''
      tags:
      - api
  /api/v1/booklist/:
    get:
      operationId: listBooks
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Books'
          description: ''
      tags:
      - api
  /api/v1/genrelist/:
    get:
      operationId: listGenres
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Genres'
          description: ''
      tags:
      - api
  /api/v1/user/:
    get:
      operationId: listUsers
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
          description: ''
      tags:
      - api
components:
  schemas:
    Authors:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        last_name:
          type: string
          description: "\u0412\u0432\u0435\u0434\u0438\u0442\u0435 \u0444\u0430\u043C\
            \u0438\u043B\u0438\u044E \u0430\u0432\u0442\u043E\u0440\u0430"
          maxLength: 100
        first_name:
          type: string
          description: "\u0412\u0432\u0435\u0434\u0438\u0442\u0435 \u0438\u043C\u044F\
            \ \u0430\u0432\u0442\u043E\u0440\u0430"
          maxLength: 100
        date_of_birth:
          type: string
          format: date
          nullable: true
          description: "\u0412\u0432\u0435\u0434\u0438\u0442\u0435 \u0434\u0430\u0442\
            \u0443 \u0440\u043E\u0436\u0434\u0435\u043D\u0438\u044F"
        about:
          type: string
          description: "\u0412\u0432\u0435\u0434\u0438\u0442\u0435 \u0441\u0432\u0435\
            \u0434\u0435\u043D\u0438\u044F \u043E\u0431 \u0430\u0432\u0442\u043E\u0440\
            \u0435"
      required:
      - last_name
      - first_name
      - about
    Books:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        title:
          type: string
          description: "\u0412\u0432\u0435\u0434\u0438\u0442\u0435 \u043D\u0430\u0437\
            \u0432\u0430\u043D\u0438\u0435 \u043A\u043D\u0438\u0433\u0438"
          maxLength: 200
        genre:
          type: integer
          nullable: true
          description: "\u0412\u044B\u0431\u0435\u0440\u0435\u0442\u0435 \u0436\u0430\
            \u043D\u0440 \u0434\u043B\u044F \u043A\u043D\u0438\u0433\u0438"
        language:
          type: integer
          nullable: true
          description: "\u0412\u044B\u0431\u0435\u0440\u0435\u0442\u0435 \u044F\u0437\
            \u044B\u043A \u043A\u043D\u0438\u0433\u0438"
        publisher:
          type: integer
          nullable: true
          description: "\u0412\u044B\u0431\u0435\u0440\u0435\u0442\u0435 \u0438\u0437\
            \u0434\u0430\u0442\u0435\u043B\u044C\u0441\u0442\u0432\u043E"
        price:
          type: string
          format: decimal
          multipleOf: 0.01
          maximum: 100000
          minimum: -100000
          description: "\u0412\u0432\u0435\u0434\u0438\u0442\u0435 \u0446\u0435\u043D\
            \u0443 \u043A\u043D\u0438\u0433\u0438"
        isbn:
          type: string
          description: "\u0414\u043E\u043B\u0436\u043D\u043E \u0441\u043E\u0434\u0435\
            \u0440\u0436\u0430\u0442\u044C 13 \u0441\u0438\u043C\u0432\u043E\u043B\
            \u043E\u0432"
          maxLength: 13
        summary:
          type: string
          description: "\u0412\u0432\u0435\u0434\u0438\u0442\u0435 \u043A\u0440\u0430\
            \u0442\u043A\u043E\u0435 \u043E\u043F\u0438\u0441\u0430\u043D\u0438\u0435\
            \ \u043A\u043D\u0438\u0433\u0438"
          maxLength: 1200
      required:
      - title
      - price
      - isbn
      - summary
    Genres:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          description: "\u0412\u0432\u0435\u0434\u0438\u0442\u0435 \u0436\u0430\u043D\
            \u0440 \u043A\u043D\u0438\u0433\u0438"
          maxLength: 200
        about:
          type: string
          nullable: true
          description: "\u0412\u0432\u0435\u0434\u0438\u0442\u0435 \u0441\u0432\u0435\
            \u0434\u0435\u043D\u0438\u044F \u043E \u0436\u0430\u043D\u0440\u0435"
      required:
      - name
    User:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        username:
          type: string
          description: "\u041E\u0431\u044F\u0437\u0430\u0442\u0435\u043B\u044C\u043D\
            \u043E\u0435 \u043F\u043E\u043B\u0435. \u041D\u0435 \u0431\u043E\u043B\
            \u0435\u0435 150 \u0441\u0438\u043C\u0432\u043E\u043B\u043E\u0432. \u0422\
            \u043E\u043B\u044C\u043A\u043E \u0431\u0443\u043A\u0432\u044B, \u0446\u0438\
            \u0444\u0440\u044B \u0438 \u0441\u0438\u043C\u0432\u043E\u043B\u044B @/./+/-/_."
          pattern: ^[\w.@+-]+\z
          maxLength: 150
        email:
          type: string
          format: email
          maxLength: 254
        is_staff:
          type: boolean
          description: "\u041E\u0442\u043C\u0435\u0442\u044C\u0442\u0435, \u0435\u0441\
            \u043B\u0438 \u043F\u043E\u043B\u044C\u0437\u043E\u0432\u0430\u0442\u0435\
            \u043B\u044C \u043C\u043E\u0436\u0435\u0442 \u0432\u0445\u043E\u0434\u0438\
            \u0442\u044C \u0432 \u0430\u0434\u043C\u0438\u043D\u0438\u0441\u0442\u0440\
            \u0430\u0442\u0438\u0432\u043D\u0443\u044E \u0447\u0430\u0441\u0442\u044C\
            \ \u0441\u0430\u0439\u0442\u0430."
      required:
      - username
